### ISSUE TITLE
Unable to create Cloudformation

### ISSUE THREAD

**Issue by samhotnumb** [awslabs/lambda-refarch-mobilebackend#6]
The following resource(s) failed to create: [tablePhotoNotes, CloudFrontDistribution, S3mobileuseruploads]. . Rollback requested by user.

**Comment by waleoladehin** [comment]
Hello, 

What bucket name did you use when you configured the CloudFormation template? Could you try overriding the default bucket name in the CloudFormation template when you're configuring it in the console? For example, "mobiles3uploaddirectory-[timestamp]". It could be the case the bucket you've created is already taken and then the template is rolling back the changes.

Let me know if that helps. Thanks.
Wale

**Comment by samhotnumb** [comment]
That seemed to work. Thanks so much for prompt response.

**Comment by waleoladehin** [comment]
Great. As a heads up you'll have a similar process for the second CloudFormation template as far as pointing to a unique bucket and referencing the lambda functions you'll upload to it. Good luck and thanks again.
